// =========================================================
// LITTLE BLOOM ACADEMY — DATA.JS
// Shared pools + 5-day weekly themed content
// =========================================================

// ── Shared helpers ────────────────────────────────────────
function pick(arr) { return arr[Math.floor(Math.random() * arr.length)]; }
function shuffle(arr) { return [...arr].sort(() => Math.random() - 0.5); }
function choices(arr, n) { return shuffle(arr).slice(0, n); }

// ── Shared content pools ──────────────────────────────────
const DATA = {

    // --- General ---
    dayNames: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
    months: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],

    weatherOptions: [
        { icon: '☀️', label: 'Sunny', bg: '#fffde7', border: '#f9a825' },
        { icon: '🌧️', label: 'Rainy', bg: '#e3f2fd', border: '#1565c0' },
        { icon: '☁️', label: 'Cloudy', bg: '#f5f5f5', border: '#757575' },
        { icon: '🌬️', label: 'Windy', bg: '#e8f5e9', border: '#2e7d32' },
        { icon: '⛈️', label: 'Stormy', bg: '#ede7f6', border: '#4527a0' },
        { icon: '🌈', label: 'Rainbow', bg: '#fce4ec', border: '#ad1457' },
    ],
    weatherFeelings: [
        { icon: '😊', label: 'Happy' }, { icon: '😴', label: 'Sleepy' },
        { icon: '😤', label: 'Excited' }, { icon: '😢', label: 'Sad' },
        { icon: '😂', label: 'Silly' }, { icon: '🤒', label: 'Not well' },
    ],
    weatherActivities: [
        'wear a raincoat?', 'play outside?', 'wear sunscreen?',
        'bring an umbrella?', 'wear a jersey?',
    ],
    calendarQuestions: [
        'What day is it today?', 'What month are we in?', 'What season is it?',
        'How many days are in a week?', 'What day comes after today?',
    ],

    // --- Full alphabet, counting icons, shapes, colours ---
    letters: [
        { letter: 'A', icon: '🍎', word: 'Apple' }, { letter: 'B', icon: '🏀', word: 'Ball' },
        { letter: 'C', icon: '🐱', word: 'Cat' }, { letter: 'D', icon: '🐶', word: 'Dog' },
        { letter: 'E', icon: '🥚', word: 'Egg' }, { letter: 'F', icon: '🐸', word: 'Frog' },
        { letter: 'G', icon: '🍇', word: 'Grapes' }, { letter: 'H', icon: '🏠', word: 'House' },
        { letter: 'I', icon: '🍦', word: 'Ice cream' }, { letter: 'J', icon: '🪁', word: 'Jump rope' },
        { letter: 'K', icon: '🪁', word: 'Kite' }, { letter: 'L', icon: '🦁', word: 'Lion' },
        { letter: 'M', icon: '🌙', word: 'Moon' }, { letter: 'N', icon: '🦅', word: 'Nest' },
        { letter: 'O', icon: '🐙', word: 'Octopus' }, { letter: 'P', icon: '🐧', word: 'Penguin' },
        { letter: 'Q', icon: '👑', word: 'Queen' }, { letter: 'R', icon: '🌈', word: 'Rainbow' },
        { letter: 'S', icon: '⭐', word: 'Star' }, { letter: 'T', icon: '🐢', word: 'Turtle' },
        { letter: 'U', icon: '☂️', word: 'Umbrella' }, { letter: 'V', icon: '🐝', word: 'Voom-voom' },
        { letter: 'W', icon: '🐳', word: 'Whale' }, { letter: 'X', icon: '🎸', word: 'Xylophone' },
        { letter: 'Y', icon: '🪀', word: 'Yo-yo' }, { letter: 'Z', icon: '🦓', word: 'Zebra' },
    ],
    countingIcons: ['🌸', '🦋', '🐝', '🍎', '⭐', '🎈', '🐟', '🌻', '🧁', '🦀', '🐞', '🍓'],
    shapes: [
        { name: 'Circle', icon: '⭕', sides: 0 }, { name: 'Triangle', icon: '🔺', sides: 3 },
        { name: 'Square', icon: '🟥', sides: 4 }, { name: 'Rectangle', icon: '🟦', sides: 4 },
        { name: 'Star', icon: '⭐', sides: 5 }, { name: 'Heart', icon: '❤️', sides: 0 },
        { name: 'Diamond', icon: '🔷', sides: 4 }, { name: 'Oval', icon: '🥚', sides: 0 },
    ],
    colours: [
        { name: 'Red', hex: '#f44336' }, { name: 'Blue', hex: '#2196F3' },
        { name: 'Green', hex: '#4CAF50' }, { name: 'Yellow', hex: '#FFEB3B' },
        { name: 'Pink', hex: '#E91E63' }, { name: 'Purple', hex: '#9C27B0' },
        { name: 'Orange', hex: '#FF9800' }, { name: 'White', hex: '#EEEEEE' },
        { name: 'Brown', hex: '#795548' }, { name: 'Black', hex: '#333333' },
    ],
    animals: [
        { name: 'Lion', icon: '🦁', sound: 'ROAR!', move: 'jump up and down', SA: true },
        { name: 'Elephant', icon: '🐘', sound: 'TRUMPET!', move: 'stomp your feet', SA: true },
        { name: 'Meerkat', icon: '🧍', sound: 'SQUEAK!', move: 'stand very still on tiptoe', SA: true },
        { name: 'Giraffe', icon: '🦒', sound: 'HMM!', move: 'stretch your arms up high', SA: true },
        { name: 'Zebra', icon: '🦓', sound: 'BARK!', move: 'gallop on the spot', SA: true },
        { name: 'Springbok', icon: '🦌', sound: 'BLEAT!', move: 'leap as high as you can', SA: true },
        { name: 'Hippo', icon: '🦛', sound: 'GRUNT!', move: 'open your mouth as wide as you can', SA: true },
        { name: 'Crocodile', icon: '🐊', sound: 'SNAP!', move: 'snap your arms like jaws', SA: true },
        { name: 'Rhino', icon: '🦏', sound: 'SNORT!', move: 'charge forward with your fist as a horn', SA: true },
        { name: 'Cheetah', icon: '🐆', sound: 'CHIRP!', move: 'run in place as fast as you can', SA: true },
        { name: 'Dog', icon: '🐶', sound: 'WOOF!', move: 'pant and wag your bottom', SA: false },
        { name: 'Cat', icon: '🐱', sound: 'MEOW!', move: 'sit and lick your paw', SA: false },
        { name: 'Frog', icon: '🐸', sound: 'RIBBIT!', move: 'jump from a crouch', SA: false },
        { name: 'Bird', icon: '🐦', sound: 'TWEET!', move: 'flap your arms and spin', SA: false },
        { name: 'Fish', icon: '🐟', sound: 'blub blub!', move: 'swim with your whole body', SA: false },
        { name: 'Rabbit', icon: '🐰', sound: 'SQUEAK!', move: 'hop hop hop on the spot', SA: false },
    ],
    rhymes: [
        { title: 'Twinkle Twinkle', lines: ['Twinkle twinkle little star ⭐', 'How I wonder what you are', 'Up above the world so high', 'Like a diamond in the sky', 'Twinkle twinkle little star ⭐'] },
        { title: 'Rain Rain Go Away', lines: ['Rain rain go away 🌧️', 'Come again another day', 'Little one wants to play', 'Rain rain go away'] },
        { title: 'Baa Baa Black Sheep', lines: ['Baa baa black sheep 🐑', 'Have you any wool?', 'Yes sir yes sir, three bags full!', 'One for the master, one for the dame', 'And one for the little girl down the lane!'] },
        { title: 'Old MacDonald', lines: ['Old MacDonald had a farm 🐄', 'E-I-E-I-O!', 'And on his farm he had a cow', 'E-I-E-I-O!', 'With a moo moo here, and a moo moo there!'] },
        { title: 'Humpty Dumpty', lines: ['Humpty Dumpty sat on a wall 🥚', 'Humpty Dumpty had a great fall!', 'All the king\'s horses and all the king\'s men', 'Couldn\'t put Humpty together again!'] },
        { title: 'Incy Wincy Spider', lines: ['Incy Wincy spider 🕷️', 'Climbed up the water spout', 'Down came the rain and washed the spider out', 'Out came the sunshine and dried up all the rain', 'Incy Wincy spider climbed up the spout again!'] },
        { title: 'Head Shoulders Knees', lines: ['Head and shoulders, knees and toes 🙋', 'Knees and toes!', 'Head and shoulders, knees and toes', 'Eyes and ears and mouth and nose!'] },
    ],
    memoryItems: [
        { icon: '📺', label: 'News Report' }, { icon: '🏺', label: 'Clay Time' },
        { icon: '🛣️', label: 'Obstacle Course' }, { icon: '🔎', label: 'Scavenger Hunt' },
        { icon: '🦁', label: 'Animal Charades' }, { icon: '📖', label: 'Story Time' },
        { icon: '🎵', label: 'Singing' }, { icon: '🌤️', label: 'Sunny Day' },
        { icon: '🍎', label: 'Letter A' }, { icon: '✨', label: 'Counting Stars' },
        { icon: '🎨', label: 'Drawing' }, { icon: '🌿', label: 'Nature Walk' },
        { icon: '🧁', label: 'Baking' }, { icon: '🎭', label: 'Drama' },
        { icon: '🧩', label: 'Puzzle Time' },
    ],
};

// ── PER-DAY WEEKLY THEME DATA ─────────────────────────────
// Each day has: theme, emoji, accentColor, focusLetters, focusNumbers,
// activities (6 parallel to sidebar slots), and full guardian tips

const WEEKLY = {

    // ── MONDAY ─────────────────────────────────────────────
    monday: {
        day: 'Monday', emoji: '🌅', accentColor: '#ffb703',
        theme: 'Our World — Introduction',
        tagline: 'A brand new week starts today!',
        focusLetters: ['A', 'B', 'C', 'D', 'E'],
        focusNumbers: [1, 2, 3, 4, 5],
        activities: {
            weather: {
                theme: 'Monday Morning Check-In',
                extraPrompts: ['Tell me one thing you did on the weekend!', 'What is your favourite food?', 'Who do you love most?'],
            },
            sculptor: {
                theme: 'Playdough Introduction',
                drawPrompt: 'Draw something from your weekend! 🏖️',
                shapeFocus: ['Circle', 'Square', 'Triangle'],
                colourFocus: ['Red', 'Blue', 'Yellow'],
            },
            obstacle: {
                theme: 'Wake-Up Body Course',
                extraQ: { question: 'Is the ball ABOVE or BELOW the box?', img: '🏐 📦', answer: 'Above', options: ['Above', 'Below', 'Inside', 'Around'] },
            },
            scavenger: {
                letters: ['A', 'B', 'C', 'D', 'E'],
                countMax: 5,
                theme: 'Find the letter — A to E',
            },
            charades: {
                animalSet: ['Lion', 'Elephant', 'Giraffe', 'Zebra', 'Dog'],
                rhymeSet: ['Twinkle Twinkle', 'Baa Baa Black Sheep'],
                theme: 'Animal Stars!',
            },
            suitcase: {
                theme: 'Monday Memory Pack',
                quizFocus: ['News Report', 'Clay Time', 'Letter A', 'Counting Stars'],
            },
        },
        guardianTips: {
            weather: { intro: 'Start the week gently. Ask her what she is looking forward to this week.', steps: ['Discuss the weather together — look outside.', 'Ask: "What day is it? What comes after Monday?"', 'Share one thing YOU are looking forward to this week.', 'Ask how she slept and how she feels.', 'Draw the weather in a notebook — start a weekly weather chart!'], extend: ["Play 'Weather Reporter' - give them a spoon as a microphone and let them report.", "Draw a 'Weather House' showing what clothes to wear in different rooms.", "Talk about extreme weather: 'What is a tornado? What is a blizzard?'", "Make a weather chart that they can update every single morning.", "Learn a weather song together on YouTube."] },
            sculptor: { intro: 'Introduce the week\'s theme through art.', steps: ['Roll clay/playdough into a ball TOGETHER.', 'Ask: "What shape is this? Can we make it flat?"', 'Give her the theme: Draw the flag of a place you want to visit.', 'Name each colour as she picks it up.', 'Ask her to show you something round, then something with corners.'] , extend: ["🏺 PINCH POT CHALLENGE (20 min) — Use real clay, playdough, or self-hardening air-dry clay. Teach her the PINCH POT technique: press your thumb into the centre of a ball of clay, then pinch the walls up slowly to form a little bowl. This is one of the oldest art techniques in the world! Once made, she can press leaves, lace, or textured objects into the walls to create a pattern. Leave to dry. When hard, she can paint it. You now have a real handmade bowl she made herself.", "🌍 MAP MAKING (25 min) — Ask her to sculpt or draw a MAP of your home from above, as if she is a bird looking down. It doesn't have to be perfect! She draws each room, the garden, the street. Add the compass points together: North, South, East, West. Ask: 'Which direction does your bedroom face? Where does the sun rise from?' Then make it a game: 'Hide a treasure somewhere in the house — mark it on the map with an X. I have to find it!' This teaches spatial reasoning and geography.", "🎭 COLLAGE PORTRAIT GALLERY (30 min) — Collect old magazines or newspapers, scissors, glue, and a big sheet of paper. Her theme: PEOPLE IN OUR COMMUNITY. She cuts out faces, clothes, buildings, and jobs to create a scene of community life. While she builds: 'Who is this person? What job do they do? How does this person help us?' When done, she presents it to you like a gallery guide: 'This is a doctor, she helps sick people...' Builds cutting skills, creativity, and social awareness.", "🌿 NATURE CAST (30 min) — Collect leaves, flowers, bark, or seed pods from outside. Press them flat. Then roll playdough flat like a pancake and press each nature item into it firmly. Peel it away carefully — the texture is perfectly captured in the clay! She creates a whole panel of nature textures. Ask: 'Which texture is roughest? Smoothest? What made these marks?' Allow to air dry. Paint with a single base colour and then dry-brush a different colour over the top to highlight the textures.", "👩‍🎨 THE ART CRITIC GAME (20 min) — Print or draw 5 simple artworks (or use ones she has already made). She becomes THE ART CRITIC. Give her a magnifying glass (even a toilet roll tube works!). For each piece she must say: One thing she LIKES, One thing she would CHANGE, One FEELING the art gives her, and One WORD she thinks the artist is trying to say. Write her reviews on paper like a real gallery. This is genuine critical thinking and emotional intelligence disguised as art!"] },
            obstacle: { intro: 'Get the body awake after the weekend!', steps: ['Do 10 jumping jacks TOGETHER before starting the screen game.', 'Use real furniture: jump over a pillow, crawl under a table.', 'Ask: "What is OVER the table?" and "What is UNDER the chair?"', 'Time her and let her try to beat her score.', 'Teach the word "beside" — put two objects beside each other.'] , extend: ["🏗️ ARCHITECT COURSE (30 min) — This time SHE designs the course. Give her 10 minutes to place pillows, chairs, tape lines, and blankets around the room to build the ultimate obstacle course. She draws a map of it on paper, gives it a name, and assigns a POINT VALUE to each obstacle (harder = more points). Then you run it. Then she runs it. Keep a running scoreboard for the week. This teaches engineering thinking, planning, and task sequencing.", "🎵 MUSICAL OBSTACLE COURSE (20 min) — Play upbeat music while running the course. The rule: when the music stops, FREEZE wherever you are — even mid-jump! When music resumes, continue. This adds a listening challenge to the physical one. Alternate: the music TEMPO controls how fast she must move — fast song = run, slow song = move in s-l-o-w motion. She loves slow motion! Teaches listening, body control, and rhythm.", "📦 BLINDFOLD NAVIGATION (15 min) — She puts on a blindfold (or closes her eyes tightly). You stand 3 steps behind her and guide her through the course using ONLY words: 'Take two steps forward. Now turn LEFT. Big step OVER the pillow. Duck DOWN under the chair.' This is powerful for language development, trust, and spatial vocabulary. Then swap roles — SHE guides you. Warning: she will absolutely try to crash you into a wall on purpose!", "⏱️ RELAY RACE FORMAT (20 min) — Turn the course into a relay with a twist. She runs one 'leg' (section) of the course, then taps your hand. You run the next leg. Keep a total team time. Then try to beat it. Vary the rules: one leg on tiptoe, one leg hopping on one foot, one leg with arms folded behind the back. Count how many 'legs' it takes to complete the course together. Great for addition skills ('That was leg 3 and leg 4 — how many total so far?').", "🌟 CHAMPIONSHIP DAY (30 min) — Build the hardest, longest, most creative course of the week. Give it a dramatic name: 'THE SUPER BLOOM CHALLENGE'. Award points for: speed, style, creativity, and sportsmanship. Print or draw a CERTIFICATE on paper afterwards: 'I hereby certify that [Name] completed the Super Bloom Challenge with outstanding bravery and athletic skill.' Sign it. This is her trophy. Frame it if you can. This is about ending the session with enormous pride."] },
            scavenger: { intro: 'Focus on A–E sounds only today.', steps: ['"A" is for Apple — find ANYTHING that starts with A!', '"B" is for Ball — clap when you name a B word.', '"C" is for Cat — can she find 3 C words?', 'Write the letters A–E on paper and she decorates each one.', 'Say a word and she must guess the first letter.'] , extend: ["📖 LETTER BOOK MAKING (30 min) — Each letter gets its own page in a homemade book. Fold 5–6 sheets of paper in half and staple or tie them together. On each page: the big letter, the small letter, a drawing of the word, and the word written out. She decorates each page her own way. By the end of the week you have her very own alphabet book. Read it at bedtime instead of a story. She authored a BOOK. That is enormous for self-esteem.", "🔊 PHONICS SOUND HUNT (20 min) — Pick one letter. Set a timer for 3 minutes. She races around the house finding as many things as possible that START with that letter sound. She must say the word out loud as she grabs it. Points for: finding it, saying the sound clearly, and using it in a sentence. 'Apple! A-A-Apple! I eat an apple for snack.' Then sort everything: objects with the same ENDING sound on one side, same STARTING sound on the other. Phonemic awareness is the #1 predictor of reading success.", "✉️ LETTER WRITING (25 min) — She writes (or dictates while you scribe) a real letter to someone she loves — grandparent, cousin, friend, or a made-up pen pal. The letter must include: a greeting, one thing she did this week, one question for the other person, and a sign-off. She decorates the envelope, addresses it, and you post it for real. OR email it with a photo of her drawing attached. Getting a reply back in a few days is magic for motivation to read and write more.", "🃏 ALPHABET WAR (CARD GAME) — Write all 26 letters on small cards (index cards or cut-up cereal boxes). Shuffle and deal equally between you two. Flip one card each at the same time. Whoever can say an animal, food, or object starting with THEIR letter FIRST wins both cards. If neither can think of one in 5 seconds, both cards go to the middle as a 'Jackpot Pile'. The next round's winner takes those too. This is a fast-paced, high-energy phonics workout disguised as a battle.", "🌍 WORLD ALPHABET ADVENTURE (20 min) — Working through the letters of the week, look up one country, city, or landmark for each letter together. 'A is for AFRICA — where is Africa on the globe? B is for BRAZIL — what animal lives there?' Use a globe, atlas, or Google Maps. She puts a finger on each place. Ask: 'Is it near or far? How would we get there? What language do they speak?' This plants seeds of global curiosity and geographical thinking that last a lifetime."] },
            charades: { intro: 'Monday energy is high — use it for big movement!', steps: ['You act an animal first, she guesses.', 'She picks an animal card, acts it, you guess.', 'After each animal: "Where does this animal live?"', 'SA focus: Lion and Elephant are game animals — are they dangerous?', 'Sing "Old MacDonald" together substituting SA animals.'] , extend: ["🎬 MINI WILDLIFE DOCUMENTARY (20 min) — She is now SIR/DAME ATTENBOROUGH. Set up a couch as the camera zone. She picks an animal, hides behind a chair, and you provide the narration: 'And here we see the magnificent LION, stealthily approaching the watering hole...' She acts it out as the wildlife. Record 2 minutes on your phone. Watch it back and add commentary. Ask: 'What does this animal eat? Where does it sleep? What are its predators?' Develop naturalistic intelligence through dramatic play.", "🦁 SOUTH AFRICAN SAFARI MAP (25 min) — Draw a BIG map of Southern Africa on a large sheet of paper together. Mark: the Kruger National Park, the Kalahari Desert, the Drakensberg Mountains, the coast. Then she draws each SA animal you have played on the map, placing them in their natural habitat. 'Does a hippo live in the desert or by the river? Does a meerkat live in the jungle or the Kalahari?' This is geography, biology, and art session in one.", "🎭 EMOTION ANIMAL THEATRE (15 min) — Pick three animals and three emotions from a hat. On pieces of paper write: LION, ELEPHANT, FROG. On separate pieces: HAPPY, SCARED, ANGRY. She draws one of each and must act out that animal having that emotion. A HAPPY LION is totally different from a SCARED LION. A FROG who is ANGRY! This teaches emotional recognition, empathy, and physical expression simultaneously. Award dramatic flair points.", "🔢 ANIMAL MATHS GAME (20 min) — Use the animals as a maths context. 'Three lions are sleeping in the sun. Two more arrive. How many lions total?' She acts out each lion. 'Five zebras are eating grass. A cheetah arrives and ROAR! — two zebras run away. How many are left?' She acts the whole scene out physically. Story-based maths with movement is scientifically proven to dramatically improve number retention in early childhood. Use this every single week.", "🎶 ANIMAL SOUND BAND (20 min) — Each of you picks two animals. Your animals make a RHYTHM together. Lion roars on beat 1, Elephant trumpets on beat 2, Frog ribbits on beat 3, Bird tweets on beat 4. Clap or drum on a pot between sounds. Build a full 4-beat-bar animal orchestra. Add complexity: what if the LION roars TWICE as fast? Change the tempo. Change the animals. She is learning rhythm, beat, and music theory through animal sounds and pure silliness."] },
            suitcase: { intro: 'Recap the WHOLE day together — this is the most important 15 minutes.', steps: ['Ask her to pick the 3 best things from today.', 'For each: "Tell me one thing you learned about that."', 'Ask: "What was HARD today? What was EASY?"', 'Ask: "What do you want to do tomorrow?"', 'Help her call Dad/Grandma and tell them ONE thing from today.'] , extend: ["📓 BLOOM JOURNAL ENTRY (20 min) — Today you write a proper journal entry together. The format: Date at the top. One drawing of the BEST moment. Three sentences: 'Today I learned... Today I felt... Tomorrow I want to...' You write her words as she dictates them if she can't write yet — or she tries herself and you help with spelling. Read it back to her. Ask: 'How do you think you'll feel reading this when you're 10 years old?' This is her autobiography in progress. It is one of the most powerful educational habits you can instil in your child.", "🗣️ TEACH IT BACK CHALLENGE (15 min) — She picks ONE thing she learned today. Her job is to teach it to an imaginary student — a toy, a pet, or YOU pretending you know nothing. The rule: use SIMPLE words as if explaining to a baby. She cannot say 'just' — she must actually explain. Research confirms that teaching something to another person is the single most effective way to consolidate learning. This exercise also builds public speaking, confidence, and organizational thinking.", "🌟 PRIDE CEREMONY (10 min) — This is a ritual that takes 10 minutes but leaves a memory that lasts years. At the end of the day, you and she face each other. She tells you: ONE thing she's proud of from today. You tell her: TWO things YOU noticed her doing well (be specific: 'When you tried the obstacle again even though you fell — that was BRAVE'). Then she gives you a score out of 10 for today and explains WHY. Shake hands like professionals. This is emotional vocabulary, self-assessment, and bonding.", "🔮 TOMORROW PLANNING SESSION (15 min) — Pull out the app and look at TOMORROW's activities together. She reads the titles with you. Ask: 'Which one are you most excited for? Which one do you think will be hardest? What question do you have about tomorrow?' Help her prepare: if there's a scavenger hunt, hide some letters in the house tonight so she can 'discover' them tomorrow. If it's art day, lay out the supplies. Children who know what to expect before a session learn dramatically more when it arrives.", "📞 VIDEO CALL SHOW AND TELL (10 min) — Call a grandparent, aunt, uncle, or family friend on video call RIGHT NOW, at the end of the day. She has 2 minutes to tell them: one thing she learned, one thing she made, and one thing she's proud of. The adult on the other end asks one question. This embeds today's learning through social sharing, which is a higher-order cognitive activity. It also makes the grandparent's day. Everybody wins. Do this at least once a week."] },
        },
    },

    // ── TUESDAY ────────────────────────────────────────────
    tuesday: {
        day: 'Tuesday', emoji: '🎨', accentColor: '#ff85a2',
        theme: 'Creative Day — Art & Imagination',
        tagline: 'Today we make beautiful things!',
        focusLetters: ['F', 'G', 'H', 'I', 'J'],
        focusNumbers: [1, 2, 3, 4, 5, 6],
        activities: {
            weather: { theme: 'Artist\'s Morning', extraPrompts: ['What colour is the sky today?', 'If the sky could be ANY colour, what would you pick?', 'Draw the weather in your mind!'] },
            sculptor: { theme: 'Big Art Project', drawPrompt: 'Create a self-portrait! Draw YOUR face 🧒', shapeFocus: ['Heart', 'Star', 'Diamond'], colourFocus: ['Pink', 'Purple', 'Orange'] },
            obstacle: { theme: 'Artist\'s Runway', extraQ: { question: 'Is the paintbrush INSIDE or OUTSIDE the pot?', img: '🖌️ 🪣', answer: 'Inside', options: ['Inside', 'Outside', 'On top', 'Beside'] } },
            scavenger: { letters: ['F', 'G', 'H', 'I', 'J'], countMax: 6, theme: 'Find the letter — F to J' },
            charades: { animalSet: ['Meerkat', 'Springbok', 'Cat', 'Rabbit', 'Bird'], rhymeSet: ['Twinkle Twinkle', 'Incy Wincy Spider'], theme: 'Creative Animal Poses!' },
            suitcase: { theme: 'Tuesday Memory Pack', quizFocus: ['Drawing', 'Story Time', 'Singing', 'Puzzle Time'] },
        },
        guardianTips: {
            weather: { intro: 'Tuesday is creative day — connect everything to colour and art.', steps: ['Ask her to name every colour she can see outside.', 'Ask: "What colour makes you feel happy? What colour makes you feel calm?"', 'Draw the weather using only shapes — no words!', 'Ask her to make up a weather "dance" (sunny = wiggle, rainy = tap fingers).', 'Name a colour and she finds something that colour in the room.'], extend: ["Play 'Weather Reporter' - give them a spoon as a microphone and let them report.", "Draw a 'Weather House' showing what clothes to wear in different rooms.", "Talk about extreme weather: 'What is a tornado? What is a blizzard?'", "Make a weather chart that they can update every single morning.", "Learn a weather song together on YouTube."] },
            sculptor: { intro: 'Big creative project day!', steps: ['Give her a BIG piece of paper and the biggest brush/crayon you have.', 'Theme: "Make a portrait of someone you love."', 'Name shapes as she draws: "That\'s a circle for the face!"', 'Ask her to tell a STORY about the picture when finished.', 'Let her choose the colours with no correction — this builds confidence.'], extend: 'Frame her artwork and put it up at home — tell her why it\'s beautiful.' , extend: ["🏺 PINCH POT CHALLENGE (20 min) — Use real clay, playdough, or self-hardening air-dry clay. Teach her the PINCH POT technique: press your thumb into the centre of a ball of clay, then pinch the walls up slowly to form a little bowl. This is one of the oldest art techniques in the world! Once made, she can press leaves, lace, or textured objects into the walls to create a pattern. Leave to dry. When hard, she can paint it. You now have a real handmade bowl she made herself.", "🌍 MAP MAKING (25 min) — Ask her to sculpt or draw a MAP of your home from above, as if she is a bird looking down. It doesn't have to be perfect! She draws each room, the garden, the street. Add the compass points together: North, South, East, West. Ask: 'Which direction does your bedroom face? Where does the sun rise from?' Then make it a game: 'Hide a treasure somewhere in the house — mark it on the map with an X. I have to find it!' This teaches spatial reasoning and geography.", "🎭 COLLAGE PORTRAIT GALLERY (30 min) — Collect old magazines or newspapers, scissors, glue, and a big sheet of paper. Her theme: PEOPLE IN OUR COMMUNITY. She cuts out faces, clothes, buildings, and jobs to create a scene of community life. While she builds: 'Who is this person? What job do they do? How does this person help us?' When done, she presents it to you like a gallery guide: 'This is a doctor, she helps sick people...' Builds cutting skills, creativity, and social awareness.", "🌿 NATURE CAST (30 min) — Collect leaves, flowers, bark, or seed pods from outside. Press them flat. Then roll playdough flat like a pancake and press each nature item into it firmly. Peel it away carefully — the texture is perfectly captured in the clay! She creates a whole panel of nature textures. Ask: 'Which texture is roughest? Smoothest? What made these marks?' Allow to air dry. Paint with a single base colour and then dry-brush a different colour over the top to highlight the textures.", "👩‍🎨 THE ART CRITIC GAME (20 min) — Print or draw 5 simple artworks (or use ones she has already made). She becomes THE ART CRITIC. Give her a magnifying glass (even a toilet roll tube works!). For each piece she must say: One thing she LIKES, One thing she would CHANGE, One FEELING the art gives her, and One WORD she thinks the artist is trying to say. Write her reviews on paper like a real gallery. This is genuine critical thinking and emotional intelligence disguised as art!"] },
            obstacle: { intro: 'Connect movement to art — be a paintbrush!', steps: ['Say "You are a GIANT paintbrush!" — she moves her whole body as if painting.', 'Fast music = small strokes (tiny jumps). Slow music = big strokes (big arm sweeps).', 'Ask "Is the couch IN FRONT of or BEHIND the table?"', 'Ask her to make a "sculpture" with her body — freeze the pose.', 'Take a photo of her best pose!'] , extend: ["🏗️ ARCHITECT COURSE (30 min) — This time SHE designs the course. Give her 10 minutes to place pillows, chairs, tape lines, and blankets around the room to build the ultimate obstacle course. She draws a map of it on paper, gives it a name, and assigns a POINT VALUE to each obstacle (harder = more points). Then you run it. Then she runs it. Keep a running scoreboard for the week. This teaches engineering thinking, planning, and task sequencing.", "🎵 MUSICAL OBSTACLE COURSE (20 min) — Play upbeat music while running the course. The rule: when the music stops, FREEZE wherever you are — even mid-jump! When music resumes, continue. This adds a listening challenge to the physical one. Alternate: the music TEMPO controls how fast she must move — fast song = run, slow song = move in s-l-o-w motion. She loves slow motion! Teaches listening, body control, and rhythm.", "📦 BLINDFOLD NAVIGATION (15 min) — She puts on a blindfold (or closes her eyes tightly). You stand 3 steps behind her and guide her through the course using ONLY words: 'Take two steps forward. Now turn LEFT. Big step OVER the pillow. Duck DOWN under the chair.' This is powerful for language development, trust, and spatial vocabulary. Then swap roles — SHE guides you. Warning: she will absolutely try to crash you into a wall on purpose!", "⏱️ RELAY RACE FORMAT (20 min) — Turn the course into a relay with a twist. She runs one 'leg' (section) of the course, then taps your hand. You run the next leg. Keep a total team time. Then try to beat it. Vary the rules: one leg on tiptoe, one leg hopping on one foot, one leg with arms folded behind the back. Count how many 'legs' it takes to complete the course together. Great for addition skills ('That was leg 3 and leg 4 — how many total so far?').", "🌟 CHAMPIONSHIP DAY (30 min) — Build the hardest, longest, most creative course of the week. Give it a dramatic name: 'THE SUPER BLOOM CHALLENGE'. Award points for: speed, style, creativity, and sportsmanship. Print or draw a CERTIFICATE on paper afterwards: 'I hereby certify that [Name] completed the Super Bloom Challenge with outstanding bravery and athletic skill.' Sign it. This is her trophy. Frame it if you can. This is about ending the session with enormous pride."] },
            scavenger: { intro: 'F–J letters today.', steps: ['"F" is for Frog — hop 3 times and say an F word!', '"G" is for Grapes — find something that starts with G.', '"H" is for House — draw a tiny house together.', '"I" is for Ice cream — if you could have any flavour, what letter does it start with?', '"J" is for Jump — count how many times she can jump in 10 seconds.'] , extend: ["📖 LETTER BOOK MAKING (30 min) — Each letter gets its own page in a homemade book. Fold 5–6 sheets of paper in half and staple or tie them together. On each page: the big letter, the small letter, a drawing of the word, and the word written out. She decorates each page her own way. By the end of the week you have her very own alphabet book. Read it at bedtime instead of a story. She authored a BOOK. That is enormous for self-esteem.", "🔊 PHONICS SOUND HUNT (20 min) — Pick one letter. Set a timer for 3 minutes. She races around the house finding as many things as possible that START with that letter sound. She must say the word out loud as she grabs it. Points for: finding it, saying the sound clearly, and using it in a sentence. 'Apple! A-A-Apple! I eat an apple for snack.' Then sort everything: objects with the same ENDING sound on one side, same STARTING sound on the other. Phonemic awareness is the #1 predictor of reading success.", "✉️ LETTER WRITING (25 min) — She writes (or dictates while you scribe) a real letter to someone she loves — grandparent, cousin, friend, or a made-up pen pal. The letter must include: a greeting, one thing she did this week, one question for the other person, and a sign-off. She decorates the envelope, addresses it, and you post it for real. OR email it with a photo of her drawing attached. Getting a reply back in a few days is magic for motivation to read and write more.", "🃏 ALPHABET WAR (CARD GAME) — Write all 26 letters on small cards (index cards or cut-up cereal boxes). Shuffle and deal equally between you two. Flip one card each at the same time. Whoever can say an animal, food, or object starting with THEIR letter FIRST wins both cards. If neither can think of one in 5 seconds, both cards go to the middle as a 'Jackpot Pile'. The next round's winner takes those too. This is a fast-paced, high-energy phonics workout disguised as a battle.", "🌍 WORLD ALPHABET ADVENTURE (20 min) — Working through the letters of the week, look up one country, city, or landmark for each letter together. 'A is for AFRICA — where is Africa on the globe? B is for BRAZIL — what animal lives there?' Use a globe, atlas, or Google Maps. She puts a finger on each place. Ask: 'Is it near or far? How would we get there? What language do they speak?' This plants seeds of global curiosity and geographical thinking that last a lifetime."] },
            charades: { intro: 'Creative movement day — be dramatic!', steps: ['Add drama: be a SCARED Meerkat, a HAPPY Springbok.', 'Ask her to make a "sad" animal face vs a "happy" animal face.', 'Invent a new animal together — what sound does it make?', 'Sing "Head Shoulders Knees" but replace body parts with animal parts.', 'She teaches YOU an animal pose you\'ve never done.'] , extend: ["🎬 MINI WILDLIFE DOCUMENTARY (20 min) — She is now SIR/DAME ATTENBOROUGH. Set up a couch as the camera zone. She picks an animal, hides behind a chair, and you provide the narration: 'And here we see the magnificent LION, stealthily approaching the watering hole...' She acts it out as the wildlife. Record 2 minutes on your phone. Watch it back and add commentary. Ask: 'What does this animal eat? Where does it sleep? What are its predators?' Develop naturalistic intelligence through dramatic play.", "🦁 SOUTH AFRICAN SAFARI MAP (25 min) — Draw a BIG map of Southern Africa on a large sheet of paper together. Mark: the Kruger National Park, the Kalahari Desert, the Drakensberg Mountains, the coast. Then she draws each SA animal you have played on the map, placing them in their natural habitat. 'Does a hippo live in the desert or by the river? Does a meerkat live in the jungle or the Kalahari?' This is geography, biology, and art session in one.", "🎭 EMOTION ANIMAL THEATRE (15 min) — Pick three animals and three emotions from a hat. On pieces of paper write: LION, ELEPHANT, FROG. On separate pieces: HAPPY, SCARED, ANGRY. She draws one of each and must act out that animal having that emotion. A HAPPY LION is totally different from a SCARED LION. A FROG who is ANGRY! This teaches emotional recognition, empathy, and physical expression simultaneously. Award dramatic flair points.", "🔢 ANIMAL MATHS GAME (20 min) — Use the animals as a maths context. 'Three lions are sleeping in the sun. Two more arrive. How many lions total?' She acts out each lion. 'Five zebras are eating grass. A cheetah arrives and ROAR! — two zebras run away. How many are left?' She acts the whole scene out physically. Story-based maths with movement is scientifically proven to dramatically improve number retention in early childhood. Use this every single week.", "🎶 ANIMAL SOUND BAND (20 min) — Each of you picks two animals. Your animals make a RHYTHM together. Lion roars on beat 1, Elephant trumpets on beat 2, Frog ribbits on beat 3, Bird tweets on beat 4. Clap or drum on a pot between sounds. Build a full 4-beat-bar animal orchestra. Add complexity: what if the LION roars TWICE as fast? Change the tempo. Change the animals. She is learning rhythm, beat, and music theory through animal sounds and pure silliness."] },
            suitcase: { intro: 'Creative recap — use drawing instead of words.', steps: ['Ask her to draw, not tell, her favourite part of today.', 'Ask: "If today was a colour, what colour would it be?"', 'Ask: "If today was an animal, which one?"', 'She shows you her drawing and you have to guess what it is.', 'Add the drawing to the Bloom Journal.'] , extend: ["📓 BLOOM JOURNAL ENTRY (20 min) — Today you write a proper journal entry together. The format: Date at the top. One drawing of the BEST moment. Three sentences: 'Today I learned... Today I felt... Tomorrow I want to...' You write her words as she dictates them if she can't write yet — or she tries herself and you help with spelling. Read it back to her. Ask: 'How do you think you'll feel reading this when you're 10 years old?' This is her autobiography in progress. It is one of the most powerful educational habits you can instil in your child.", "🗣️ TEACH IT BACK CHALLENGE (15 min) — She picks ONE thing she learned today. Her job is to teach it to an imaginary student — a toy, a pet, or YOU pretending you know nothing. The rule: use SIMPLE words as if explaining to a baby. She cannot say 'just' — she must actually explain. Research confirms that teaching something to another person is the single most effective way to consolidate learning. This exercise also builds public speaking, confidence, and organizational thinking.", "🌟 PRIDE CEREMONY (10 min) — This is a ritual that takes 10 minutes but leaves a memory that lasts years. At the end of the day, you and she face each other. She tells you: ONE thing she's proud of from today. You tell her: TWO things YOU noticed her doing well (be specific: 'When you tried the obstacle again even though you fell — that was BRAVE'). Then she gives you a score out of 10 for today and explains WHY. Shake hands like professionals. This is emotional vocabulary, self-assessment, and bonding.", "🔮 TOMORROW PLANNING SESSION (15 min) — Pull out the app and look at TOMORROW's activities together. She reads the titles with you. Ask: 'Which one are you most excited for? Which one do you think will be hardest? What question do you have about tomorrow?' Help her prepare: if there's a scavenger hunt, hide some letters in the house tonight so she can 'discover' them tomorrow. If it's art day, lay out the supplies. Children who know what to expect before a session learn dramatically more when it arrives.", "📞 VIDEO CALL SHOW AND TELL (10 min) — Call a grandparent, aunt, uncle, or family friend on video call RIGHT NOW, at the end of the day. She has 2 minutes to tell them: one thing she learned, one thing she made, and one thing she's proud of. The adult on the other end asks one question. This embeds today's learning through social sharing, which is a higher-order cognitive activity. It also makes the grandparent's day. Everybody wins. Do this at least once a week."] },
        },
    },

    // ── WEDNESDAY ──────────────────────────────────────────
    wednesday: {
        day: 'Wednesday', emoji: '🌿', accentColor: '#52b788',
        theme: 'Science & Discovery Day',
        tagline: 'Let\'s explore and discover today!',
        focusLetters: ['K', 'L', 'M', 'N', 'O'],
        focusNumbers: [1, 2, 3, 4, 5, 6, 7],
        activities: {
            weather: { theme: 'Scientist\'s Weather Station', extraPrompts: ['Is it hot or cold outside?', 'What do clouds look like today?', 'Can you feel wind on your skin?'] },
            sculptor: { theme: 'Nature Sculpting', drawPrompt: 'Draw a plant or animal from outside 🌿', shapeFocus: ['Oval', 'Triangle', 'Circle'], colourFocus: ['Green', 'Brown', 'Blue'] },
            obstacle: { theme: 'Nature Explorer Trail', extraQ: { question: 'Is the butterfly ABOVE or ON the flower?', img: '🦋 🌸', answer: 'Above', options: ['Above', 'On', 'Under', 'Beside'] } },
            scavenger: { letters: ['K', 'L', 'M', 'N', 'O'], countMax: 7, theme: 'Find the letter — K to O' },
            charades: { animalSet: ['Rhino', 'Hippo', 'Crocodile', 'Fish', 'Frog'], rhymeSet: ['Rain Rain Go Away', 'Incy Wincy Spider'], theme: 'Water & Wild Animals!' },
            suitcase: { theme: 'Wednesday Discovery Pack', quizFocus: ['Nature Walk', 'Counting Stars', 'Obstacle Course', 'Scavenger Hunt'] },
        },
        guardianTips: {
            weather: { intro: 'Science day — everything is an experiment!', steps: ['Go outside for 2 minutes and observe the weather together.', 'Feel the air: "Is it humid? Dry? Can you smell rain?"', 'Ask: "What do YOU think the weather will be tomorrow?"', 'Look at clouds together — name their shapes.', 'Start a "Weather diary" — she draws tomorrow\'s prediction.'], extend: ["Play 'Weather Reporter' - give them a spoon as a microphone and let them report.", "Draw a 'Weather House' showing what clothes to wear in different rooms.", "Talk about extreme weather: 'What is a tornado? What is a blizzard?'", "Make a weather chart that they can update every single morning.", "Learn a weather song together on YouTube."] },
            sculptor: { intro: 'Nature sensory play.', steps: ['Collect 5 items from outside: leaf, stick, pebble, flower, soil.', 'Feel each one: "Is it smooth, rough, soft, hard?"', 'Use the items to make a nature COLLAGE on paper with glue.', 'Ask: "Where does this come from? Is it from a plant or an animal?"', 'Sort the items by size, colour, or texture.'] , extend: ["🏺 PINCH POT CHALLENGE (20 min) — Use real clay, playdough, or self-hardening air-dry clay. Teach her the PINCH POT technique: press your thumb into the centre of a ball of clay, then pinch the walls up slowly to form a little bowl. This is one of the oldest art techniques in the world! Once made, she can press leaves, lace, or textured objects into the walls to create a pattern. Leave to dry. When hard, she can paint it. You now have a real handmade bowl she made herself.", "🌍 MAP MAKING (25 min) — Ask her to sculpt or draw a MAP of your home from above, as if she is a bird looking down. It doesn't have to be perfect! She draws each room, the garden, the street. Add the compass points together: North, South, East, West. Ask: 'Which direction does your bedroom face? Where does the sun rise from?' Then make it a game: 'Hide a treasure somewhere in the house — mark it on the map with an X. I have to find it!' This teaches spatial reasoning and geography.", "🎭 COLLAGE PORTRAIT GALLERY (30 min) — Collect old magazines or newspapers, scissors, glue, and a big sheet of paper. Her theme: PEOPLE IN OUR COMMUNITY. She cuts out faces, clothes, buildings, and jobs to create a scene of community life. While she builds: 'Who is this person? What job do they do? How does this person help us?' When done, she presents it to you like a gallery guide: 'This is a doctor, she helps sick people...' Builds cutting skills, creativity, and social awareness.", "🌿 NATURE CAST (30 min) — Collect leaves, flowers, bark, or seed pods from outside. Press them flat. Then roll playdough flat like a pancake and press each nature item into it firmly. Peel it away carefully — the texture is perfectly captured in the clay! She creates a whole panel of nature textures. Ask: 'Which texture is roughest? Smoothest? What made these marks?' Allow to air dry. Paint with a single base colour and then dry-brush a different colour over the top to highlight the textures.", "👩‍🎨 THE ART CRITIC GAME (20 min) — Print or draw 5 simple artworks (or use ones she has already made). She becomes THE ART CRITIC. Give her a magnifying glass (even a toilet roll tube works!). For each piece she must say: One thing she LIKES, One thing she would CHANGE, One FEELING the art gives her, and One WORD she thinks the artist is trying to say. Write her reviews on paper like a real gallery. This is genuine critical thinking and emotional intelligence disguised as art!"] },
            obstacle: { intro: 'Explorer movement circuit.', steps: ['Pretend to be a scientist on a nature trek.', 'Ask: "What is a mountain? Can you climb like you\'re on a mountain?"', 'Find something NEXT TO the wall, something BEHIND the door.', 'Ask: "Is the sun ABOVE us or BELOW us?"', 'Measure things using her foot as a "unit" — how many feet long is the couch?'] , extend: ["🏗️ ARCHITECT COURSE (30 min) — This time SHE designs the course. Give her 10 minutes to place pillows, chairs, tape lines, and blankets around the room to build the ultimate obstacle course. She draws a map of it on paper, gives it a name, and assigns a POINT VALUE to each obstacle (harder = more points). Then you run it. Then she runs it. Keep a running scoreboard for the week. This teaches engineering thinking, planning, and task sequencing.", "🎵 MUSICAL OBSTACLE COURSE (20 min) — Play upbeat music while running the course. The rule: when the music stops, FREEZE wherever you are — even mid-jump! When music resumes, continue. This adds a listening challenge to the physical one. Alternate: the music TEMPO controls how fast she must move — fast song = run, slow song = move in s-l-o-w motion. She loves slow motion! Teaches listening, body control, and rhythm.", "📦 BLINDFOLD NAVIGATION (15 min) — She puts on a blindfold (or closes her eyes tightly). You stand 3 steps behind her and guide her through the course using ONLY words: 'Take two steps forward. Now turn LEFT. Big step OVER the pillow. Duck DOWN under the chair.' This is powerful for language development, trust, and spatial vocabulary. Then swap roles — SHE guides you. Warning: she will absolutely try to crash you into a wall on purpose!", "⏱️ RELAY RACE FORMAT (20 min) — Turn the course into a relay with a twist. She runs one 'leg' (section) of the course, then taps your hand. You run the next leg. Keep a total team time. Then try to beat it. Vary the rules: one leg on tiptoe, one leg hopping on one foot, one leg with arms folded behind the back. Count how many 'legs' it takes to complete the course together. Great for addition skills ('That was leg 3 and leg 4 — how many total so far?').", "🌟 CHAMPIONSHIP DAY (30 min) — Build the hardest, longest, most creative course of the week. Give it a dramatic name: 'THE SUPER BLOOM CHALLENGE'. Award points for: speed, style, creativity, and sportsmanship. Print or draw a CERTIFICATE on paper afterwards: 'I hereby certify that [Name] completed the Super Bloom Challenge with outstanding bravery and athletic skill.' Sign it. This is her trophy. Frame it if you can. This is about ending the session with enormous pride."] },
            scavenger: { intro: 'K-O sounds today — connect to nature.', steps: ['"K" is for Kite — what shape is a kite, and what does it DO?', '"L" is for Lion — describe what a Lion looks like without naming it.', '"M" is for Moon — is the moon out at night or during the day? Why?', '"N" is for Nest — what animals live in nests?', '"O" is for Octopus — how many arms does it have? Count to 8 together!'] , extend: ["📖 LETTER BOOK MAKING (30 min) — Each letter gets its own page in a homemade book. Fold 5–6 sheets of paper in half and staple or tie them together. On each page: the big letter, the small letter, a drawing of the word, and the word written out. She decorates each page her own way. By the end of the week you have her very own alphabet book. Read it at bedtime instead of a story. She authored a BOOK. That is enormous for self-esteem.", "🔊 PHONICS SOUND HUNT (20 min) — Pick one letter. Set a timer for 3 minutes. She races around the house finding as many things as possible that START with that letter sound. She must say the word out loud as she grabs it. Points for: finding it, saying the sound clearly, and using it in a sentence. 'Apple! A-A-Apple! I eat an apple for snack.' Then sort everything: objects with the same ENDING sound on one side, same STARTING sound on the other. Phonemic awareness is the #1 predictor of reading success.", "✉️ LETTER WRITING (25 min) — She writes (or dictates while you scribe) a real letter to someone she loves — grandparent, cousin, friend, or a made-up pen pal. The letter must include: a greeting, one thing she did this week, one question for the other person, and a sign-off. She decorates the envelope, addresses it, and you post it for real. OR email it with a photo of her drawing attached. Getting a reply back in a few days is magic for motivation to read and write more.", "🃏 ALPHABET WAR (CARD GAME) — Write all 26 letters on small cards (index cards or cut-up cereal boxes). Shuffle and deal equally between you two. Flip one card each at the same time. Whoever can say an animal, food, or object starting with THEIR letter FIRST wins both cards. If neither can think of one in 5 seconds, both cards go to the middle as a 'Jackpot Pile'. The next round's winner takes those too. This is a fast-paced, high-energy phonics workout disguised as a battle.", "🌍 WORLD ALPHABET ADVENTURE (20 min) — Working through the letters of the week, look up one country, city, or landmark for each letter together. 'A is for AFRICA — where is Africa on the globe? B is for BRAZIL — what animal lives there?' Use a globe, atlas, or Google Maps. She puts a finger on each place. Ask: 'Is it near or far? How would we get there? What language do they speak?' This plants seeds of global curiosity and geographical thinking that last a lifetime."] },
            charades: { intro: 'Water animals and wild beasts today.', steps: ['Hippo: blow bubbles in a cup of water together.', 'Crocodile: snap your arms like jaws in slow motion.', 'Frog: jump across the room counting how many jumps.', 'Fish: "swim" across the floor on your tummies.', 'Ask: "Which of these animals can swim? Which can\'t?"'] , extend: ["🎬 MINI WILDLIFE DOCUMENTARY (20 min) — She is now SIR/DAME ATTENBOROUGH. Set up a couch as the camera zone. She picks an animal, hides behind a chair, and you provide the narration: 'And here we see the magnificent LION, stealthily approaching the watering hole...' She acts it out as the wildlife. Record 2 minutes on your phone. Watch it back and add commentary. Ask: 'What does this animal eat? Where does it sleep? What are its predators?' Develop naturalistic intelligence through dramatic play.", "🦁 SOUTH AFRICAN SAFARI MAP (25 min) — Draw a BIG map of Southern Africa on a large sheet of paper together. Mark: the Kruger National Park, the Kalahari Desert, the Drakensberg Mountains, the coast. Then she draws each SA animal you have played on the map, placing them in their natural habitat. 'Does a hippo live in the desert or by the river? Does a meerkat live in the jungle or the Kalahari?' This is geography, biology, and art session in one.", "🎭 EMOTION ANIMAL THEATRE (15 min) — Pick three animals and three emotions from a hat. On pieces of paper write: LION, ELEPHANT, FROG. On separate pieces: HAPPY, SCARED, ANGRY. She draws one of each and must act out that animal having that emotion. A HAPPY LION is totally different from a SCARED LION. A FROG who is ANGRY! This teaches emotional recognition, empathy, and physical expression simultaneously. Award dramatic flair points.", "🔢 ANIMAL MATHS GAME (20 min) — Use the animals as a maths context. 'Three lions are sleeping in the sun. Two more arrive. How many lions total?' She acts out each lion. 'Five zebras are eating grass. A cheetah arrives and ROAR! — two zebras run away. How many are left?' She acts the whole scene out physically. Story-based maths with movement is scientifically proven to dramatically improve number retention in early childhood. Use this every single week.", "🎶 ANIMAL SOUND BAND (20 min) — Each of you picks two animals. Your animals make a RHYTHM together. Lion roars on beat 1, Elephant trumpets on beat 2, Frog ribbits on beat 3, Bird tweets on beat 4. Clap or drum on a pot between sounds. Build a full 4-beat-bar animal orchestra. Add complexity: what if the LION roars TWICE as fast? Change the tempo. Change the animals. She is learning rhythm, beat, and music theory through animal sounds and pure silliness."] },
            suitcase: { intro: 'Wednesday is halfway through the week — great time to reflect!', steps: ['Ask: "What is the most interesting thing you discovered this week so far?"', 'Ask: "What does a scientist DO?"', 'Play "I Spy" with nature words: "I spy something that is green and has leaves."', 'Ask her to explain ONE thing she learned to a toy or teddy.', 'Draw a "brain map" together — what\'s inside her head after this week?'] , extend: ["📓 BLOOM JOURNAL ENTRY (20 min) — Today you write a proper journal entry together. The format: Date at the top. One drawing of the BEST moment. Three sentences: 'Today I learned... Today I felt... Tomorrow I want to...' You write her words as she dictates them if she can't write yet — or she tries herself and you help with spelling. Read it back to her. Ask: 'How do you think you'll feel reading this when you're 10 years old?' This is her autobiography in progress. It is one of the most powerful educational habits you can instil in your child.", "🗣️ TEACH IT BACK CHALLENGE (15 min) — She picks ONE thing she learned today. Her job is to teach it to an imaginary student — a toy, a pet, or YOU pretending you know nothing. The rule: use SIMPLE words as if explaining to a baby. She cannot say 'just' — she must actually explain. Research confirms that teaching something to another person is the single most effective way to consolidate learning. This exercise also builds public speaking, confidence, and organizational thinking.", "🌟 PRIDE CEREMONY (10 min) — This is a ritual that takes 10 minutes but leaves a memory that lasts years. At the end of the day, you and she face each other. She tells you: ONE thing she's proud of from today. You tell her: TWO things YOU noticed her doing well (be specific: 'When you tried the obstacle again even though you fell — that was BRAVE'). Then she gives you a score out of 10 for today and explains WHY. Shake hands like professionals. This is emotional vocabulary, self-assessment, and bonding.", "🔮 TOMORROW PLANNING SESSION (15 min) — Pull out the app and look at TOMORROW's activities together. She reads the titles with you. Ask: 'Which one are you most excited for? Which one do you think will be hardest? What question do you have about tomorrow?' Help her prepare: if there's a scavenger hunt, hide some letters in the house tonight so she can 'discover' them tomorrow. If it's art day, lay out the supplies. Children who know what to expect before a session learn dramatically more when it arrives.", "📞 VIDEO CALL SHOW AND TELL (10 min) — Call a grandparent, aunt, uncle, or family friend on video call RIGHT NOW, at the end of the day. She has 2 minutes to tell them: one thing she learned, one thing she made, and one thing she's proud of. The adult on the other end asks one question. This embeds today's learning through social sharing, which is a higher-order cognitive activity. It also makes the grandparent's day. Everybody wins. Do this at least once a week."] },
        },
    },

    // ── THURSDAY ───────────────────────────────────────────
    thursday: {
        day: 'Thursday', emoji: '💪', accentColor: '#8ecae6',
        theme: 'Body & Movement Day',
        tagline: 'Move your body and feel strong!',
        focusLetters: ['P', 'Q', 'R', 'S', 'T'],
        focusNumbers: [1, 2, 3, 4, 5, 6, 7, 8],
        activities: {
            weather: { theme: 'Active Morning', extraPrompts: ['Do 5 star jumps before we start!', 'What body part feels strong today?', 'What sport would you like to play today?'] },
            sculptor: { theme: 'Body Art', drawPrompt: 'Draw a superhero — that\'s YOU! 💪', shapeFocus: ['Rectangle', 'Diamond', 'Star'], colourFocus: ['Blue', 'Red', 'Green', 'Yellow'] },
            obstacle: { theme: 'Mega Obstacle Challenge', extraQ: { question: 'Is the hula hoop AROUND or AWAY FROM you?', img: '🤸 ⭕', answer: 'Around', options: ['Around', 'Away from', 'On top of', 'Under'] } },
            scavenger: { letters: ['P', 'Q', 'R', 'S', 'T'], countMax: 8, theme: 'Find the letter — P to T' },
            charades: { animalSet: ['Cheetah', 'Springbok', 'Rabbit', 'Frog', 'Bird'], rhymeSet: ['Head Shoulders Knees', 'Humpty Dumpty'], theme: 'Fast & Slow Animals!' },
            suitcase: { theme: 'Thursday Power Pack', quizFocus: ['Obstacle Course', 'Animal Charades', 'Drawing', 'Singing'] },
        },
        guardianTips: {
            weather: { intro: 'High energy day — match her enthusiasm!', steps: ['Do a "weather workout" — sunny = jumping jacks, rainy = running on the spot.', 'Ask: "What sport could you play in this weather?"', 'Ask: "What does your body feel like before exercise vs after?"', 'Name a sport: she must act it out.', 'Ask: "How many jumping jacks can you do before you need to breathe?"'], extend: ["Play 'Weather Reporter' - give them a spoon as a microphone and let them report.", "Draw a 'Weather House' showing what clothes to wear in different rooms.", "Talk about extreme weather: 'What is a tornado? What is a blizzard?'", "Make a weather chart that they can update every single morning.", "Learn a weather song together on YouTube."] },
            sculptor: { intro: 'Body awareness through art.', steps: ['Trace her hand and she decorates it with patterns.', 'Ask: "How many fingers? How many knuckles?"', 'Draw a superhero body together — where are the muscles?', 'Talk about body parts: "What does your heart do? Your lungs?"', 'Ask her to draw what she looks like when she\'s running.'] , extend: ["🏺 PINCH POT CHALLENGE (20 min) — Use real clay, playdough, or self-hardening air-dry clay. Teach her the PINCH POT technique: press your thumb into the centre of a ball of clay, then pinch the walls up slowly to form a little bowl. This is one of the oldest art techniques in the world! Once made, she can press leaves, lace, or textured objects into the walls to create a pattern. Leave to dry. When hard, she can paint it. You now have a real handmade bowl she made herself.", "🌍 MAP MAKING (25 min) — Ask her to sculpt or draw a MAP of your home from above, as if she is a bird looking down. It doesn't have to be perfect! She draws each room, the garden, the street. Add the compass points together: North, South, East, West. Ask: 'Which direction does your bedroom face? Where does the sun rise from?' Then make it a game: 'Hide a treasure somewhere in the house — mark it on the map with an X. I have to find it!' This teaches spatial reasoning and geography.", "🎭 COLLAGE PORTRAIT GALLERY (30 min) — Collect old magazines or newspapers, scissors, glue, and a big sheet of paper. Her theme: PEOPLE IN OUR COMMUNITY. She cuts out faces, clothes, buildings, and jobs to create a scene of community life. While she builds: 'Who is this person? What job do they do? How does this person help us?' When done, she presents it to you like a gallery guide: 'This is a doctor, she helps sick people...' Builds cutting skills, creativity, and social awareness.", "🌿 NATURE CAST (30 min) — Collect leaves, flowers, bark, or seed pods from outside. Press them flat. Then roll playdough flat like a pancake and press each nature item into it firmly. Peel it away carefully — the texture is perfectly captured in the clay! She creates a whole panel of nature textures. Ask: 'Which texture is roughest? Smoothest? What made these marks?' Allow to air dry. Paint with a single base colour and then dry-brush a different colour over the top to highlight the textures.", "👩‍🎨 THE ART CRITIC GAME (20 min) — Print or draw 5 simple artworks (or use ones she has already made). She becomes THE ART CRITIC. Give her a magnifying glass (even a toilet roll tube works!). For each piece she must say: One thing she LIKES, One thing she would CHANGE, One FEELING the art gives her, and One WORD she thinks the artist is trying to say. Write her reviews on paper like a real gallery. This is genuine critical thinking and emotional intelligence disguised as art!"] },
            obstacle: { intro: 'Maximum movement today!', steps: ['Time the course three times — can she beat her record?', 'Add a new obstacle each round: balance beam (tape on floor), tunnel (blanket over chairs).', 'Use FULL spatial language: "Go THROUGH the tunnel, then AROUND the pillow."', 'Ask: "Which is more tiring — going OVER or going UNDER?"', 'Count her steps between each obstacle.'] , extend: ["🏗️ ARCHITECT COURSE (30 min) — This time SHE designs the course. Give her 10 minutes to place pillows, chairs, tape lines, and blankets around the room to build the ultimate obstacle course. She draws a map of it on paper, gives it a name, and assigns a POINT VALUE to each obstacle (harder = more points). Then you run it. Then she runs it. Keep a running scoreboard for the week. This teaches engineering thinking, planning, and task sequencing.", "🎵 MUSICAL OBSTACLE COURSE (20 min) — Play upbeat music while running the course. The rule: when the music stops, FREEZE wherever you are — even mid-jump! When music resumes, continue. This adds a listening challenge to the physical one. Alternate: the music TEMPO controls how fast she must move — fast song = run, slow song = move in s-l-o-w motion. She loves slow motion! Teaches listening, body control, and rhythm.", "📦 BLINDFOLD NAVIGATION (15 min) — She puts on a blindfold (or closes her eyes tightly). You stand 3 steps behind her and guide her through the course using ONLY words: 'Take two steps forward. Now turn LEFT. Big step OVER the pillow. Duck DOWN under the chair.' This is powerful for language development, trust, and spatial vocabulary. Then swap roles — SHE guides you. Warning: she will absolutely try to crash you into a wall on purpose!", "⏱️ RELAY RACE FORMAT (20 min) — Turn the course into a relay with a twist. She runs one 'leg' (section) of the course, then taps your hand. You run the next leg. Keep a total team time. Then try to beat it. Vary the rules: one leg on tiptoe, one leg hopping on one foot, one leg with arms folded behind the back. Count how many 'legs' it takes to complete the course together. Great for addition skills ('That was leg 3 and leg 4 — how many total so far?').", "🌟 CHAMPIONSHIP DAY (30 min) — Build the hardest, longest, most creative course of the week. Give it a dramatic name: 'THE SUPER BLOOM CHALLENGE'. Award points for: speed, style, creativity, and sportsmanship. Print or draw a CERTIFICATE on paper afterwards: 'I hereby certify that [Name] completed the Super Bloom Challenge with outstanding bravery and athletic skill.' Sign it. This is her trophy. Frame it if you can. This is about ending the session with enormous pride."] },
            scavenger: { intro: 'P-T sounds — energetic connections!', steps: ['"P" is for Penguin — waddle across the room!', '"Q" is for Queen — sit very still and tall like royalty.', '"R" is for Run — how fast can she spell R-U-N while running on the spot?', '"S" is for Star — do star jumps while you call out S words.', '"T" is for Turtle — who can move slowest across the room?'] , extend: ["📖 LETTER BOOK MAKING (30 min) — Each letter gets its own page in a homemade book. Fold 5–6 sheets of paper in half and staple or tie them together. On each page: the big letter, the small letter, a drawing of the word, and the word written out. She decorates each page her own way. By the end of the week you have her very own alphabet book. Read it at bedtime instead of a story. She authored a BOOK. That is enormous for self-esteem.", "🔊 PHONICS SOUND HUNT (20 min) — Pick one letter. Set a timer for 3 minutes. She races around the house finding as many things as possible that START with that letter sound. She must say the word out loud as she grabs it. Points for: finding it, saying the sound clearly, and using it in a sentence. 'Apple! A-A-Apple! I eat an apple for snack.' Then sort everything: objects with the same ENDING sound on one side, same STARTING sound on the other. Phonemic awareness is the #1 predictor of reading success.", "✉️ LETTER WRITING (25 min) — She writes (or dictates while you scribe) a real letter to someone she loves — grandparent, cousin, friend, or a made-up pen pal. The letter must include: a greeting, one thing she did this week, one question for the other person, and a sign-off. She decorates the envelope, addresses it, and you post it for real. OR email it with a photo of her drawing attached. Getting a reply back in a few days is magic for motivation to read and write more.", "🃏 ALPHABET WAR (CARD GAME) — Write all 26 letters on small cards (index cards or cut-up cereal boxes). Shuffle and deal equally between you two. Flip one card each at the same time. Whoever can say an animal, food, or object starting with THEIR letter FIRST wins both cards. If neither can think of one in 5 seconds, both cards go to the middle as a 'Jackpot Pile'. The next round's winner takes those too. This is a fast-paced, high-energy phonics workout disguised as a battle.", "🌍 WORLD ALPHABET ADVENTURE (20 min) — Working through the letters of the week, look up one country, city, or landmark for each letter together. 'A is for AFRICA — where is Africa on the globe? B is for BRAZIL — what animal lives there?' Use a globe, atlas, or Google Maps. She puts a finger on each place. Ask: 'Is it near or far? How would we get there? What language do they speak?' This plants seeds of global curiosity and geographical thinking that last a lifetime."] },
            charades: { intro: 'Speed and strength theme today.', steps: ['Cheetah: sprint across the room and FREEZE when you shout stop.', 'Springbok: pronk (leap with all 4 limbs) — try it together!', 'Play "Freeze Dance" — music on, she dances; music off, she freezes as an animal.', 'Count "who can hold the stillest pose longest" — guardian vs child.', 'Silly round: be a SLOW cheetah, a TINY elephant.'] , extend: ["🎬 MINI WILDLIFE DOCUMENTARY (20 min) — She is now SIR/DAME ATTENBOROUGH. Set up a couch as the camera zone. She picks an animal, hides behind a chair, and you provide the narration: 'And here we see the magnificent LION, stealthily approaching the watering hole...' She acts it out as the wildlife. Record 2 minutes on your phone. Watch it back and add commentary. Ask: 'What does this animal eat? Where does it sleep? What are its predators?' Develop naturalistic intelligence through dramatic play.", "🦁 SOUTH AFRICAN SAFARI MAP (25 min) — Draw a BIG map of Southern Africa on a large sheet of paper together. Mark: the Kruger National Park, the Kalahari Desert, the Drakensberg Mountains, the coast. Then she draws each SA animal you have played on the map, placing them in their natural habitat. 'Does a hippo live in the desert or by the river? Does a meerkat live in the jungle or the Kalahari?' This is geography, biology, and art session in one.", "🎭 EMOTION ANIMAL THEATRE (15 min) — Pick three animals and three emotions from a hat. On pieces of paper write: LION, ELEPHANT, FROG. On separate pieces: HAPPY, SCARED, ANGRY. She draws one of each and must act out that animal having that emotion. A HAPPY LION is totally different from a SCARED LION. A FROG who is ANGRY! This teaches emotional recognition, empathy, and physical expression simultaneously. Award dramatic flair points.", "🔢 ANIMAL MATHS GAME (20 min) — Use the animals as a maths context. 'Three lions are sleeping in the sun. Two more arrive. How many lions total?' She acts out each lion. 'Five zebras are eating grass. A cheetah arrives and ROAR! — two zebras run away. How many are left?' She acts the whole scene out physically. Story-based maths with movement is scientifically proven to dramatically improve number retention in early childhood. Use this every single week.", "🎶 ANIMAL SOUND BAND (20 min) — Each of you picks two animals. Your animals make a RHYTHM together. Lion roars on beat 1, Elephant trumpets on beat 2, Frog ribbits on beat 3, Bird tweets on beat 4. Clap or drum on a pot between sounds. Build a full 4-beat-bar animal orchestra. Add complexity: what if the LION roars TWICE as fast? Change the tempo. Change the animals. She is learning rhythm, beat, and music theory through animal sounds and pure silliness."] },
            suitcase: { intro: 'Body-themed recap.', steps: ['Ask: "Which part of your body worked the hardest today?"', 'Ask: "Can you touch your toes? Your elbow? Your funny bone?"', 'Play "Simon Says" with body parts.', 'Ask: "What do you eat to make your body strong?"', 'Talk about sleep: "Your body grows when you sleep! How many hours did you sleep?"'] , extend: ["📓 BLOOM JOURNAL ENTRY (20 min) — Today you write a proper journal entry together. The format: Date at the top. One drawing of the BEST moment. Three sentences: 'Today I learned... Today I felt... Tomorrow I want to...' You write her words as she dictates them if she can't write yet — or she tries herself and you help with spelling. Read it back to her. Ask: 'How do you think you'll feel reading this when you're 10 years old?' This is her autobiography in progress. It is one of the most powerful educational habits you can instil in your child.", "🗣️ TEACH IT BACK CHALLENGE (15 min) — She picks ONE thing she learned today. Her job is to teach it to an imaginary student — a toy, a pet, or YOU pretending you know nothing. The rule: use SIMPLE words as if explaining to a baby. She cannot say 'just' — she must actually explain. Research confirms that teaching something to another person is the single most effective way to consolidate learning. This exercise also builds public speaking, confidence, and organizational thinking.", "🌟 PRIDE CEREMONY (10 min) — This is a ritual that takes 10 minutes but leaves a memory that lasts years. At the end of the day, you and she face each other. She tells you: ONE thing she's proud of from today. You tell her: TWO things YOU noticed her doing well (be specific: 'When you tried the obstacle again even though you fell — that was BRAVE'). Then she gives you a score out of 10 for today and explains WHY. Shake hands like professionals. This is emotional vocabulary, self-assessment, and bonding.", "🔮 TOMORROW PLANNING SESSION (15 min) — Pull out the app and look at TOMORROW's activities together. She reads the titles with you. Ask: 'Which one are you most excited for? Which one do you think will be hardest? What question do you have about tomorrow?' Help her prepare: if there's a scavenger hunt, hide some letters in the house tonight so she can 'discover' them tomorrow. If it's art day, lay out the supplies. Children who know what to expect before a session learn dramatically more when it arrives.", "📞 VIDEO CALL SHOW AND TELL (10 min) — Call a grandparent, aunt, uncle, or family friend on video call RIGHT NOW, at the end of the day. She has 2 minutes to tell them: one thing she learned, one thing she made, and one thing she's proud of. The adult on the other end asks one question. This embeds today's learning through social sharing, which is a higher-order cognitive activity. It also makes the grandparent's day. Everybody wins. Do this at least once a week."] },
        },
    },

    // ── FRIDAY ─────────────────────────────────────────────
    friday: {
        day: 'Friday', emoji: '🎉', accentColor: '#b7e4c7',
        theme: 'Celebration Friday — Review & Play',
        tagline: 'You made it through the week — let\'s celebrate!',
        focusLetters: ['U', 'V', 'W', 'X', 'Y', 'Z'],
        focusNumbers: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
        activities: {
            weather: { theme: 'Friday Celebration Report', extraPrompts: ['Name ONE amazing thing you did this week!', 'What day comes after Friday?', 'What will you do this weekend?'] },
            sculptor: { theme: 'Week Masterpiece', drawPrompt: 'Draw your FAVOURITE thing from this week! 🏆', shapeFocus: ['Circle', 'Star', 'Heart', 'Diamond'], colourFocus: ['Yellow', 'Orange', 'Pink', 'Purple'] },
            obstacle: { theme: 'Championship Obstacle Course', extraQ: { question: 'Is the trophy ABOVE or ON the shelf?', img: '🏆 🪑', answer: 'On', options: ['On', 'Above', 'Under', 'Beside'] } },
            scavenger: { letters: ['U', 'V', 'W', 'X', 'Y', 'Z'], countMax: 10, theme: 'Find the letter — U to Z (Final Round!)' },
            charades: { animalSet: ['Lion', 'Meerkat', 'Springbok', 'Elephant', 'Giraffe', 'Zebra'], rhymeSet: ['Old MacDonald', 'Head Shoulders Knees', 'Twinkle Twinkle'], theme: 'SA Animal Parade — Full Cast!' },
            suitcase: { theme: 'Weekly Trophy Pack', quizFocus: ['News Report', 'Drawing', 'Animal Charades', 'Nature Walk', 'Letter A', 'Counting Stars', 'Obstacle Course', 'Scavenger Hunt'] },
        },
        guardianTips: {
            weather: { intro: 'Friday is celebratory — big smiles and high fives all morning!', steps: ['Do a "week in review" — name one thing for each day of the week.', 'Make a special morning drink together (hot chocolate, smoothie).', 'Ask: "What SEASON is it? What months are in this season?"', 'Talk about the weekend — what is the plan?', 'Give her 3 genuine compliments about her work THIS WEEK.'], extend: ["Play 'Weather Reporter' - give them a spoon as a microphone and let them report.", "Draw a 'Weather House' showing what clothes to wear in different rooms.", "Talk about extreme weather: 'What is a tornado? What is a blizzard?'", "Make a weather chart that they can update every single morning.", "Learn a weather song together on YouTube."] },
            sculptor: { intro: 'Week\'s best art project.', steps: ['Big idea: make a collage of the WHOLE week — one image per day.', 'Use scissors, glue, scraps of paper, old magazines.', 'Ask: "What was your favourite lesson this week?"', 'Let her direct: "You be the helper, I make the decisions."', 'Frame the finished piece — it goes up at home!'], extend: 'Plan next week\'s art theme together — she picks the topic.' , extend: ["🏺 PINCH POT CHALLENGE (20 min) — Use real clay, playdough, or self-hardening air-dry clay. Teach her the PINCH POT technique: press your thumb into the centre of a ball of clay, then pinch the walls up slowly to form a little bowl. This is one of the oldest art techniques in the world! Once made, she can press leaves, lace, or textured objects into the walls to create a pattern. Leave to dry. When hard, she can paint it. You now have a real handmade bowl she made herself.", "🌍 MAP MAKING (25 min) — Ask her to sculpt or draw a MAP of your home from above, as if she is a bird looking down. It doesn't have to be perfect! She draws each room, the garden, the street. Add the compass points together: North, South, East, West. Ask: 'Which direction does your bedroom face? Where does the sun rise from?' Then make it a game: 'Hide a treasure somewhere in the house — mark it on the map with an X. I have to find it!' This teaches spatial reasoning and geography.", "🎭 COLLAGE PORTRAIT GALLERY (30 min) — Collect old magazines or newspapers, scissors, glue, and a big sheet of paper. Her theme: PEOPLE IN OUR COMMUNITY. She cuts out faces, clothes, buildings, and jobs to create a scene of community life. While she builds: 'Who is this person? What job do they do? How does this person help us?' When done, she presents it to you like a gallery guide: 'This is a doctor, she helps sick people...' Builds cutting skills, creativity, and social awareness.", "🌿 NATURE CAST (30 min) — Collect leaves, flowers, bark, or seed pods from outside. Press them flat. Then roll playdough flat like a pancake and press each nature item into it firmly. Peel it away carefully — the texture is perfectly captured in the clay! She creates a whole panel of nature textures. Ask: 'Which texture is roughest? Smoothest? What made these marks?' Allow to air dry. Paint with a single base colour and then dry-brush a different colour over the top to highlight the textures.", "👩‍🎨 THE ART CRITIC GAME (20 min) — Print or draw 5 simple artworks (or use ones she has already made). She becomes THE ART CRITIC. Give her a magnifying glass (even a toilet roll tube works!). For each piece she must say: One thing she LIKES, One thing she would CHANGE, One FEELING the art gives her, and One WORD she thinks the artist is trying to say. Write her reviews on paper like a real gallery. This is genuine critical thinking and emotional intelligence disguised as art!"] },
            obstacle: { intro: 'Championship day — go all out!', steps: ['Build the BIGGEST obstacle course yet — use EVERY room.', 'Let her design the course — she places the obstacles.', 'Invite a sibling, pet, or teddy to "compete."', 'Give out a certificate at the end (draw one on paper!).', 'Ask: "What new obstacle would you add if you could?"'] , extend: ["🏗️ ARCHITECT COURSE (30 min) — This time SHE designs the course. Give her 10 minutes to place pillows, chairs, tape lines, and blankets around the room to build the ultimate obstacle course. She draws a map of it on paper, gives it a name, and assigns a POINT VALUE to each obstacle (harder = more points). Then you run it. Then she runs it. Keep a running scoreboard for the week. This teaches engineering thinking, planning, and task sequencing.", "🎵 MUSICAL OBSTACLE COURSE (20 min) — Play upbeat music while running the course. The rule: when the music stops, FREEZE wherever you are — even mid-jump! When music resumes, continue. This adds a listening challenge to the physical one. Alternate: the music TEMPO controls how fast she must move — fast song = run, slow song = move in s-l-o-w motion. She loves slow motion! Teaches listening, body control, and rhythm.", "📦 BLINDFOLD NAVIGATION (15 min) — She puts on a blindfold (or closes her eyes tightly). You stand 3 steps behind her and guide her through the course using ONLY words: 'Take two steps forward. Now turn LEFT. Big step OVER the pillow. Duck DOWN under the chair.' This is powerful for language development, trust, and spatial vocabulary. Then swap roles — SHE guides you. Warning: she will absolutely try to crash you into a wall on purpose!", "⏱️ RELAY RACE FORMAT (20 min) — Turn the course into a relay with a twist. She runs one 'leg' (section) of the course, then taps your hand. You run the next leg. Keep a total team time. Then try to beat it. Vary the rules: one leg on tiptoe, one leg hopping on one foot, one leg with arms folded behind the back. Count how many 'legs' it takes to complete the course together. Great for addition skills ('That was leg 3 and leg 4 — how many total so far?').", "🌟 CHAMPIONSHIP DAY (30 min) — Build the hardest, longest, most creative course of the week. Give it a dramatic name: 'THE SUPER BLOOM CHALLENGE'. Award points for: speed, style, creativity, and sportsmanship. Print or draw a CERTIFICATE on paper afterwards: 'I hereby certify that [Name] completed the Super Bloom Challenge with outstanding bravery and athletic skill.' Sign it. This is her trophy. Frame it if you can. This is about ending the session with enormous pride."] },
            scavenger: { intro: 'Final letters of the alphabet!', steps: ['U,V,W,X,Y,Z are tricky — make it silly and playful.', 'X challenge: name ONE X word (X-ray, xylophone) and act it out.', 'Z challenge: ZAP everything you touch for 1 minute!', 'Sing the full alphabet song together, clapping on every letter.', 'Test RANDOM letters — she has 3 seconds to name the word!'] , extend: ["📖 LETTER BOOK MAKING (30 min) — Each letter gets its own page in a homemade book. Fold 5–6 sheets of paper in half and staple or tie them together. On each page: the big letter, the small letter, a drawing of the word, and the word written out. She decorates each page her own way. By the end of the week you have her very own alphabet book. Read it at bedtime instead of a story. She authored a BOOK. That is enormous for self-esteem.", "🔊 PHONICS SOUND HUNT (20 min) — Pick one letter. Set a timer for 3 minutes. She races around the house finding as many things as possible that START with that letter sound. She must say the word out loud as she grabs it. Points for: finding it, saying the sound clearly, and using it in a sentence. 'Apple! A-A-Apple! I eat an apple for snack.' Then sort everything: objects with the same ENDING sound on one side, same STARTING sound on the other. Phonemic awareness is the #1 predictor of reading success.", "✉️ LETTER WRITING (25 min) — She writes (or dictates while you scribe) a real letter to someone she loves — grandparent, cousin, friend, or a made-up pen pal. The letter must include: a greeting, one thing she did this week, one question for the other person, and a sign-off. She decorates the envelope, addresses it, and you post it for real. OR email it with a photo of her drawing attached. Getting a reply back in a few days is magic for motivation to read and write more.", "🃏 ALPHABET WAR (CARD GAME) — Write all 26 letters on small cards (index cards or cut-up cereal boxes). Shuffle and deal equally between you two. Flip one card each at the same time. Whoever can say an animal, food, or object starting with THEIR letter FIRST wins both cards. If neither can think of one in 5 seconds, both cards go to the middle as a 'Jackpot Pile'. The next round's winner takes those too. This is a fast-paced, high-energy phonics workout disguised as a battle.", "🌍 WORLD ALPHABET ADVENTURE (20 min) — Working through the letters of the week, look up one country, city, or landmark for each letter together. 'A is for AFRICA — where is Africa on the globe? B is for BRAZIL — what animal lives there?' Use a globe, atlas, or Google Maps. She puts a finger on each place. Ask: 'Is it near or far? How would we get there? What language do they speak?' This plants seeds of global curiosity and geographical thinking that last a lifetime."] },
            charades: { intro: 'SA Animal PARADE — biggest game of the week!', steps: ['Everyone in the family gets an animal.', 'Make a "parade" — march around the room in character.', 'Play the "freeze" game with ALL the SA animals.', 'Nature quiz: "Which is bigger — an elephant or a hippo?"', 'Award "Animal of the Week" — she picks her favourite SA animal and draws it.'] , extend: ["🎬 MINI WILDLIFE DOCUMENTARY (20 min) — She is now SIR/DAME ATTENBOROUGH. Set up a couch as the camera zone. She picks an animal, hides behind a chair, and you provide the narration: 'And here we see the magnificent LION, stealthily approaching the watering hole...' She acts it out as the wildlife. Record 2 minutes on your phone. Watch it back and add commentary. Ask: 'What does this animal eat? Where does it sleep? What are its predators?' Develop naturalistic intelligence through dramatic play.", "🦁 SOUTH AFRICAN SAFARI MAP (25 min) — Draw a BIG map of Southern Africa on a large sheet of paper together. Mark: the Kruger National Park, the Kalahari Desert, the Drakensberg Mountains, the coast. Then she draws each SA animal you have played on the map, placing them in their natural habitat. 'Does a hippo live in the desert or by the river? Does a meerkat live in the jungle or the Kalahari?' This is geography, biology, and art session in one.", "🎭 EMOTION ANIMAL THEATRE (15 min) — Pick three animals and three emotions from a hat. On pieces of paper write: LION, ELEPHANT, FROG. On separate pieces: HAPPY, SCARED, ANGRY. She draws one of each and must act out that animal having that emotion. A HAPPY LION is totally different from a SCARED LION. A FROG who is ANGRY! This teaches emotional recognition, empathy, and physical expression simultaneously. Award dramatic flair points.", "🔢 ANIMAL MATHS GAME (20 min) — Use the animals as a maths context. 'Three lions are sleeping in the sun. Two more arrive. How many lions total?' She acts out each lion. 'Five zebras are eating grass. A cheetah arrives and ROAR! — two zebras run away. How many are left?' She acts the whole scene out physically. Story-based maths with movement is scientifically proven to dramatically improve number retention in early childhood. Use this every single week.", "🎶 ANIMAL SOUND BAND (20 min) — Each of you picks two animals. Your animals make a RHYTHM together. Lion roars on beat 1, Elephant trumpets on beat 2, Frog ribbits on beat 3, Bird tweets on beat 4. Clap or drum on a pot between sounds. Build a full 4-beat-bar animal orchestra. Add complexity: what if the LION roars TWICE as fast? Change the tempo. Change the animals. She is learning rhythm, beat, and music theory through animal sounds and pure silliness."] },
            suitcase: { intro: 'FULL WEEK recap — this moment is golden.', steps: ['She tells you ONE thing from each day: Monday, Tuesday, Wednesday, Thursday, Friday.', 'Ask: "Which day was your favourite? Why?"', 'Ask: "What was the hardest thing you did?"', 'Ask: "What do you want to learn NEXT week?"', 'Celebrate with a small reward — a sticker, an extra story, or 20 minutes of her favourite show.'] , extend: ["📓 BLOOM JOURNAL ENTRY (20 min) — Today you write a proper journal entry together. The format: Date at the top. One drawing of the BEST moment. Three sentences: 'Today I learned... Today I felt... Tomorrow I want to...' You write her words as she dictates them if she can't write yet — or she tries herself and you help with spelling. Read it back to her. Ask: 'How do you think you'll feel reading this when you're 10 years old?' This is her autobiography in progress. It is one of the most powerful educational habits you can instil in your child.", "🗣️ TEACH IT BACK CHALLENGE (15 min) — She picks ONE thing she learned today. Her job is to teach it to an imaginary student — a toy, a pet, or YOU pretending you know nothing. The rule: use SIMPLE words as if explaining to a baby. She cannot say 'just' — she must actually explain. Research confirms that teaching something to another person is the single most effective way to consolidate learning. This exercise also builds public speaking, confidence, and organizational thinking.", "🌟 PRIDE CEREMONY (10 min) — This is a ritual that takes 10 minutes but leaves a memory that lasts years. At the end of the day, you and she face each other. She tells you: ONE thing she's proud of from today. You tell her: TWO things YOU noticed her doing well (be specific: 'When you tried the obstacle again even though you fell — that was BRAVE'). Then she gives you a score out of 10 for today and explains WHY. Shake hands like professionals. This is emotional vocabulary, self-assessment, and bonding.", "🔮 TOMORROW PLANNING SESSION (15 min) — Pull out the app and look at TOMORROW's activities together. She reads the titles with you. Ask: 'Which one are you most excited for? Which one do you think will be hardest? What question do you have about tomorrow?' Help her prepare: if there's a scavenger hunt, hide some letters in the house tonight so she can 'discover' them tomorrow. If it's art day, lay out the supplies. Children who know what to expect before a session learn dramatically more when it arrives.", "📞 VIDEO CALL SHOW AND TELL (10 min) — Call a grandparent, aunt, uncle, or family friend on video call RIGHT NOW, at the end of the day. She has 2 minutes to tell them: one thing she learned, one thing she made, and one thing she's proud of. The adult on the other end asks one question. This embeds today's learning through social sharing, which is a higher-order cognitive activity. It also makes the grandparent's day. Everybody wins. Do this at least once a week."] },
        },
    },
};
