import os

filepath = r"c:\Work\Ninny\data.js"
with open(filepath, 'r', encoding='utf-8') as f:
    content = f.read()

# The script previously generated `extend: ['string with 'quotes'', ...]`
# We will use regex to find arrays inside `extend: [...]` and ensure they are properly escaped,
# or simply change the outer quotes to double quotes.
import re

def fix_quotes(match):
    array_content = match.group(1)
    
    # We will find all string items inside the array, which are currently wrapped in single quotes: '...'
    # Some internal words also use single quotes.
    # To fix this, let's just do a naive replace of the broken formatting generated by the previous script:
    # The previous script did: f"'{s}'"
    # We will replace all instances of `'` with `"` for the strings.
    
    # A safer way: run the entire generation step again but using double quotes `"..."` for the array elements!
    return match.group(0) # We will actually just rewrite the original script to use json.dumps

# Let's write a better patch script:
